name: Tests & Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=. test/
          coverage report --fail-under=80

      - name: Generate coverage HTML (optional)
        run: coverage html

      - name: Lint code (optional)
        run: |
          pip install flake8
          flake8 .
